import {language} from './i18n.js';

const copy = {
  ro: {
    eyebrow:'UN UNIVERS DE DESCOPERIT', title:'Creează lecții care', accent:'prind viață.',
    lead:'Quiz-uri, potrivire, sortare, ordonare și memory. Ideile tale devin experiențe pe care copiii abia așteaptă să le exploreze.',
    create:'Creează o activitate', explore:'Explorează modelele', note:'Încearcă un joc chiar aici. Apoi creează-l pe al tău.',
    badge:'JOACĂ ȘI DESCOPERĂ', quiz:'Animale sălbatice', subtitle:'Un mic exemplu. Curiozitate cât cuprinde.',
    animals:['Leul','Elefantul','Girafa','Zebra'], questions:['Care este cel mai mare animal terestru?','Cine are dungi albe și negre?','Cine ajunge la frunzele de sus cu gâtul său lung?'],
    hint:'Alege un animal.', wrong:'Mai încearcă! Privește cu atenție animalele.', correct:'Exact! Ai descoperit răspunsul.', next:'Următoarea întrebare', done:'Trei descoperiri. O aventură reușită!', replay:'Joacă din nou', complete:'Ai răspuns la toate cele trei întrebări.',
    sound:'Sunete', motion:'Animații', theme:'Schimbă modul luminos / întunecat', ready:'SPAȚIUL TĂU DE LUCRU', work:'Mai departe, în atelier.', workText:'Pregătește activitățile și întâmpină fiecare copil cu un bun venit.',
  },
  en: {
    eyebrow:'A UNIVERSE TO DISCOVER',title:'Create lessons that',accent:'come to life.',lead:'Quizzes, matching, sorting, sequencing and memory. Turn your ideas into experiences children cannot wait to explore.',create:'Create an activity',explore:'Explore templates',note:'Try a game right here. Then create your own.',badge:'PLAY AND DISCOVER',quiz:'Wild animals',subtitle:'A little example. A world of curiosity.',animals:['Lion','Elephant','Giraffe','Zebra'],questions:['What is the largest land animal?','Which animal has black and white stripes?','Who reaches high leaves with a long neck?'],hint:'Choose an animal.',wrong:'Try again! Look carefully at the animals.',correct:'Exactly! You found the answer.',next:'Next question',done:'Three discoveries. One great adventure!',replay:'Play again',complete:'You answered all three questions.',sound:'Sounds',motion:'Animations',theme:'Switch light / dark mode',ready:'YOUR WORKSPACE',work:'Onwards, to your workshop.',workText:'Prepare activities and give every child a warm welcome.'
  },
  hu: {
    eyebrow:'FELFEDEZÉSRE VÁRÓ VILÁG',title:'Alkoss órákat, amelyek',accent:'életre kelnek.',lead:'Kvízek, párosítás, válogatás, sorba rendezés és memóriajáték. Ötleteidből élmények születnek, amelyeket a gyerekek örömmel fedeznek fel.',create:'Feladat létrehozása',explore:'Minták felfedezése',note:'Próbálj ki egy játékot itt, majd készíts sajátot.',badge:'JÁTSSZ ÉS FEDEZZ FEL',quiz:'Vadállatok',subtitle:'Egy kis példa. Sok-sok kíváncsiság.',animals:['Oroszlán','Elefánt','Zsiráf','Zebra'],questions:['Melyik a legnagyobb szárazföldi állat?','Melyik állatnak vannak fekete-fehér csíkjai?','Ki éri el a magas leveleket hosszú nyakával?'],hint:'Válassz egy állatot.',wrong:'Próbáld újra! Nézd meg alaposan az állatokat.',correct:'Pontosan! Megtaláltad a választ.',next:'Következő kérdés',done:'Három felfedezés. Nagyszerű kaland!',replay:'Újrajátszás',complete:'Mindhárom kérdést megválaszoltad.',sound:'Hangok',motion:'Animációk',theme:'Világos / sötét mód váltása',ready:'A TE MUNKATERED',work:'Irány a műhely!',workText:'Készíts feladatokat, és köszönts minden gyermeket szeretettel.'
  },
  it: {
    eyebrow:'UN UNIVERSO DA SCOPRIRE',title:'Crea lezioni che',accent:'prendono vita.',lead:'Quiz, abbinamenti, classificazioni, sequenze e memory. Le tue idee diventano esperienze che i bambini non vedono l’ora di esplorare.',create:'Crea un’attività',explore:'Esplora i modelli',note:'Prova un gioco qui. Poi crea il tuo.',badge:'GIOCA E SCOPRI',quiz:'Animali selvatici',subtitle:'Un piccolo esempio. Un mondo di curiosità.',animals:['Leone','Elefante','Giraffa','Zebra'],questions:['Qual è il più grande animale terrestre?','Chi ha strisce bianche e nere?','Chi raggiunge le foglie più alte con il suo lungo collo?'],hint:'Scegli un animale.',wrong:'Riprova! Osserva bene gli animali.',correct:'Esatto! Hai trovato la risposta.',next:'Prossima domanda',done:'Tre scoperte. Una splendida avventura!',replay:'Gioca ancora',complete:'Hai risposto a tutte e tre le domande.',sound:'Suoni',motion:'Animazioni',theme:'Cambia modalità chiara / scura',ready:'IL TUO SPAZIO DI LAVORO',work:'Avanti, nel laboratorio.',workText:'Prepara le attività e dai un caloroso benvenuto a ogni bambino.'
  },
  es: {
    eyebrow:'UN UNIVERSO POR DESCUBRIR',title:'Crea lecciones que',accent:'cobran vida.',lead:'Cuestionarios, parejas, clasificación, secuencias y memoria. Tus ideas se convierten en experiencias que los niños querrán explorar.',create:'Crear una actividad',explore:'Explorar modelos',note:'Prueba un juego aquí. Después crea el tuyo.',badge:'JUEGA Y DESCUBRE',quiz:'Animales salvajes',subtitle:'Un pequeño ejemplo. Un mundo de curiosidad.',animals:['León','Elefante','Jirafa','Cebra'],questions:['¿Cuál es el animal terrestre más grande?','¿Quién tiene rayas blancas y negras?','¿Quién alcanza las hojas altas con su largo cuello?'],hint:'Elige un animal.',wrong:'¡Inténtalo de nuevo! Mira bien los animales.',correct:'¡Exacto! Has encontrado la respuesta.',next:'Siguiente pregunta',done:'Tres descubrimientos. ¡Una gran aventura!',replay:'Jugar de nuevo',complete:'Has respondido las tres preguntas.',sound:'Sonidos',motion:'Animaciones',theme:'Cambiar modo claro / oscuro',ready:'TU ESPACIO DE TRABAJO',work:'Seguimos en el taller.',workText:'Prepara actividades y da la bienvenida a cada niño.'
  },
  fr: {
    eyebrow:'UN UNIVERS À DÉCOUVRIR',title:'Créez des leçons qui',accent:'prennent vie.',lead:'Quiz, associations, tri, séquences et memory. Vos idées deviennent des expériences que les enfants ont hâte d’explorer.',create:'Créer une activité',explore:'Explorer les modèles',note:'Essayez un jeu ici. Puis créez le vôtre.',badge:'JOUEZ ET DÉCOUVREZ',quiz:'Animaux sauvages',subtitle:'Un petit exemple. Un monde de curiosité.',animals:['Lion','Éléphant','Girafe','Zèbre'],questions:['Quel est le plus grand animal terrestre ?','Qui a des rayures noires et blanches ?','Qui atteint les feuilles en hauteur avec son long cou ?'],hint:'Choisissez un animal.',wrong:'Réessayez ! Regardez bien les animaux.',correct:'Exactement ! Vous avez trouvé la réponse.',next:'Question suivante',done:'Trois découvertes. Une belle aventure !',replay:'Rejouer',complete:'Vous avez répondu aux trois questions.',sound:'Sons',motion:'Animations',theme:'Changer le mode clair / sombre',ready:'VOTRE ESPACE DE TRAVAIL',work:'Continuons dans l’atelier.',workText:'Préparez vos activités et accueillez chaque enfant chaleureusement.'
  }
};
export const experienceCopy = copy[language] || copy.ro;
